"""
Company Coaching Session Model

Stores AI-generated company-specific interview coaching sessions.

Requirements: 29.9
"""
from sqlalchemy import Column, Integer, String, JSON, DateTime, ForeignKey, Index
from sqlalchemy.orm import relationship
from datetime import datetime
from app.models.base import Base


class CompanyCoachingSession(Base):
    """Company coaching session generated by AI agent"""
    
    __tablename__ = 'company_coaching_sessions'
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey('users.id', ondelete='CASCADE'), nullable=False)
    company_name = Column(String(200), nullable=False, index=True)
    target_role = Column(String(200), nullable=True)
    
    # Coaching data (JSONB)
    coaching_data = Column(JSON, nullable=False)
    # Structure:
    # {
    #   "company_overview": {
    #     "culture": str,
    #     "values": [str],
    #     "interview_style": str,
    #     "hiring_process": str
    #   },
    #   "predicted_questions": [
    #     {
    #       "question": str,
    #       "category": str,
    #       "difficulty": str,
    #       "why_asked": str
    #     }
    #   ],
    #   "star_examples": [
    #     {
    #       "situation": str,
    #       "task": str,
    #       "action": str,
    #       "result": str,
    #       "relevant_to": str
    #     }
    #   ],
    #   "confidence_tips": [str],
    #   "pre_interview_checklist": [str]
    # }
    
    # Agent execution metadata
    agent_reasoning = Column(JSON, nullable=True)  # Agent's reasoning steps
    execution_time_ms = Column(Integer, nullable=False)  # Execution time in milliseconds
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # Relationships
    user = relationship("User", back_populates="company_coaching_sessions")
    
    # Indexes for performance
    __table_args__ = (
        Index('idx_company_coaching_user_created', 'user_id', 'created_at'),
        Index('idx_company_coaching_company', 'company_name'),
    )
    
    def __repr__(self):
        return f"<CompanyCoachingSession(id={self.id}, user_id={self.user_id}, company='{self.company_name}')>"
    
    @property
    def company_overview(self):
        """Get company overview from coaching data"""
        return self.coaching_data.get('company_overview', {})
    
    @property
    def predicted_questions(self):
        """Get predicted questions from coaching data"""
        return self.coaching_data.get('predicted_questions', [])
    
    @property
    def star_examples(self):
        """Get STAR examples from coaching data"""
        return self.coaching_data.get('star_examples', [])
    
    @property
    def confidence_tips(self):
        """Get confidence tips from coaching data"""
        return self.coaching_data.get('confidence_tips', [])
    
    @property
    def pre_interview_checklist(self):
        """Get pre-interview checklist from coaching data"""
        return self.coaching_data.get('pre_interview_checklist', [])
